### ISSUE TITLE
fish imputation？

### ISSUE THREAD

**Issue by kundr** [iyhaoo/DISC#5]
Hello, this URL about your fish’s imputation cannot be clicked.
https://github.com/iyhaoo/DISC/blob/master/reproducibility/tutorials/run_imputation.md

Best wishes!

**Comment by iyhaoo** [comment]
Thanks for your using of DISC!
Yes, I renamed many files to make the file structure more simple and clear. Where do you find this link? Could you please specifiy it for me so that I can locate it more easily :)

**Comment by kundr** [comment]
Hello, I got it from the Tutorial: MELANOMA link under Gene Expression Structures (FISH) in evaluations in your README.rst file. Its URL is https://raw.githack.com/iyhaoo/DISC /master/reproducibility/Data%20Structure%20Recovery%20Evaluation/Gene%20Expression%20Structures_MELANOMA.nb.html. On this page, there is an after imputation step after Load data, and this link cannot be opened. Thank you very much for your reply。
Best wishes!

**Comment by iyhaoo** [comment]
Yes, this file is exactly what it should point into (now have fixed).
Thanks for your super careful checking. Have a nice weekend and please enjoy DISC! :D
